server:
  port: 9011
spring:
  application:
    name: page
  rabbitmq:
    host: 192.168.200.128
  main:
    allow-bean-definition-overriding: true #当遇到相同名字时是否允许覆盖注册

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka
  instance:
    prefer-ip-address: true

feign:
  hystrix:
    enabled: false
  client:
    config:
      default: #配置全局的fegin的调用时间，如果有指定的服务配置。默认的配置不会生效
        connectTimeout: 600000 #指定的是消费者连接服务提供者的连接超时时间，是否能连接，单位是毫秒
        readTimeout: 600000 #指定的是调用服务提供者的服务的超时时间，单位是毫秒

#hystrix的配置
hystrix:
  command:
    default:
      execution:
        timeout:
          #如果enabled设置为false，则请求超时交给ribbon控制
          enabled: true
        isolation:
          strategy: SEMAPHORE

#生成静态页的位置
pagepath: E:\items